import {
  Activity,
  Binary,
  Braces,
  Clock,
  Code2,
  Dices,
  FileJson,
  FileType,
  GitCompare,
  Globe2,
  Hash,
  KeyRound,
  Link,
  Palette,
  Regex,
  Ruler,
  Shield,
  Terminal,
  Type,
} from "lucide-react";
import { ICON_SIZE } from "@/shared/utils/icon-size";

/** 工具图标映射（导出供 DevToolsView 使用） */
export const TOOL_ICONS: Record<string, React.ReactNode> = {
  "json-format": <Braces size={ICON_SIZE.LARGE} />,
  "json-to-ts": <FileJson size={ICON_SIZE.LARGE} />,
  "json-path": <Braces size={ICON_SIZE.LARGE} />,
  "yaml-json": <FileJson size={ICON_SIZE.LARGE} />,
  "csv-json": <FileType size={ICON_SIZE.LARGE} />,
  "jwt-decoder": <KeyRound size={ICON_SIZE.LARGE} />,
  "basic-auth": <Shield size={ICON_SIZE.LARGE} />,
  "sql-format": <Terminal size={ICON_SIZE.LARGE} />,
  "url-parse": <Globe2 size={ICON_SIZE.LARGE} />,
  "url-query": <Globe2 size={ICON_SIZE.LARGE} />,
  "url-codec": <Link size={ICON_SIZE.LARGE} />,
  "curl-fetch": <Terminal size={ICON_SIZE.LARGE} />,
  "http-status": <Activity size={ICON_SIZE.LARGE} />,
  "http-header": <Globe2 size={ICON_SIZE.LARGE} />,
  "ua-parse": <Globe2 size={ICON_SIZE.LARGE} />,
  "base64-codec": <Binary size={ICON_SIZE.LARGE} />,
  "html-entity": <Code2 size={ICON_SIZE.LARGE} />,
  "string-escape": <Code2 size={ICON_SIZE.LARGE} />,
  "regex-test": <Regex size={ICON_SIZE.LARGE} />,
  "text-diff": <GitCompare size={ICON_SIZE.LARGE} />,
  "case-convert": <Type size={ICON_SIZE.LARGE} />,
  "text-stats": <Type size={ICON_SIZE.LARGE} />,
  timestamp: <Clock size={ICON_SIZE.LARGE} />,
  cron: <Clock size={ICON_SIZE.LARGE} />,
  hash: <Shield size={ICON_SIZE.LARGE} />,
  radix: <Hash size={ICON_SIZE.LARGE} />,
  "css-unit": <Ruler size={ICON_SIZE.LARGE} />,
  "color-preview": <Palette size={ICON_SIZE.LARGE} />,
  "mime-type": <FileType size={ICON_SIZE.LARGE} />,
  "random-gen": <Dices size={ICON_SIZE.LARGE} />,
};
